# Generated by Django 3.2.4 on 2021-07-13 15:36

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('calendarauto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericHourBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour_type', models.CharField(default='BL', max_length=2)),
                ('datetime', models.DateTimeField(verbose_name='Hour Representative')),
                ('isFilled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='GenericTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=100)),
                ('task_description', models.CharField(max_length=300)),
                ('deadline', models.DateTimeField(verbose_name='Deadline')),
                ('do_after', models.DateTimeField(default=datetime.datetime(2021, 7, 13, 15, 36, 44, 278837, tzinfo=utc), verbose_name='Do After')),
                ('est_time_to_complete', models.TimeField(verbose_name='est. time to complete')),
                ('completed', models.BooleanField(default=False)),
                ('location', models.CharField(max_length=300)),
                ('scheduled', models.BooleanField(default=False)),
                ('time_created', models.DateTimeField(default=datetime.datetime(2021, 7, 13, 15, 36, 44, 278837, tzinfo=utc), verbose_name='Time Created')),
            ],
            options={
                'get_latest_by': 'publication_date',
            },
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.AddField(
            model_name='generichourblock',
            name='current_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendarauto.generictask'),
        ),
    ]
