# Generated by Django 3.2.4 on 2021-07-26 15:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('calendarauto', '0002_auto_20210713_1136'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generictask',
            options={'get_latest_by': 'time_created'},
        ),
        migrations.AlterField(
            model_name='generichourblock',
            name='current_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='calendarauto.generictask'),
        ),
        migrations.AlterField(
            model_name='generictask',
            name='do_after',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Do After'),
        ),
        migrations.AlterField(
            model_name='generictask',
            name='task_description',
            field=models.CharField(default='None', max_length=300),
        ),
        migrations.AlterField(
            model_name='generictask',
            name='task_name',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='generictask',
            name='time_created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Time Created'),
        ),
    ]
