# Generated by Django 3.2.4 on 2021-07-27 17:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('calendarauto', '0003_auto_20210726_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generictask',
            name='deadline',
            field=models.DateTimeField(null=True, verbose_name='Deadline'),
        ),
        migrations.AlterField(
            model_name='generictask',
            name='do_after',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Do After'),
        ),
    ]
