# Generated by Django 3.2.4 on 2021-07-29 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarauto', '0004_auto_20210727_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generictask',
            name='est_time_to_complete',
            field=models.DurationField(verbose_name='est. time to complete'),
        ),
    ]
